version: "3.8"

services:
  ms-usuarios:
    build:
      context: ../ms-usuarios/
      # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: ./Dockerfile
    ports:
      - 9100:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-dandb:3306/dan
      - spring.profiles.active=default
    networks:
      - dan-db-network
    # deploy:
    #   mode: replicated
    #   replicas: 2

  ms-productos:
    build:
      context: ../ms-productos/
      # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: ./Dockerfile
    ports:
      - 9200:3000
    environment:
      - DB_PASS="***"
      - DB_USER="user"
      - DB_NAME="db"
      - DB_PORT="5432"
    networks:
      - dan-db-network

  ms-pedidos:
    build:
      context: ../ms-pedidos/
      # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: ./Dockerfile
    ports:
      - 9300:8080
    environment:
      - SPRING_DATASOURCE_URL=mongodb://root:danpwd@localhost:27017/dan-pedidos?authSource=admin
      - spring.profiles.active=default
    networks:
      - dan-db-network
  #  deploy:
  #    mode: replicated
  #    replicas: 2

  #Descomentar cuando se tenga la ui
  #dan-appui:
  #  container_name: dan-appui
  #  build:
  #    context: ../dan-appui/
  # Use an image built from the specified dockerfile in the `polling-app-server` directory.
  #    dockerfile: ./Dockerfile
  #  ports:
  #    - 9400:3000
  #  networks:
  #    - dan-db-network

networks:
  dan-db-network:
    driver: bridge
