version: '3.8'

services:
  mysql-dandb:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: danrootpassword
      MYSQL_DATABASE: dan
      MYSQL_USER: danuser
      MYSQL_PASSWORD: danpassword
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dan-db-network

  phpmyadmin-dan:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container-general
    environment:
      PMA_HOST: mysql-dandb
      PMA_USER: danuser
      PMA_PASSWORD: danpassword
    ports:
      - "8086:80"
    depends_on:
      - mysql-dandb
    networks:
      - dan-db-network

networks:
  dan-db-network:
    driver: bridge
